### ISSUE TITLE
UI/UX Design

### ISSUE THREAD

**Issue by noahjames404** [kieruu/cart-sidebar-nav#3]
![image](https://user-images.githubusercontent.com/37204262/71318331-73310a00-2487-11ea-847d-d1d325deeb6d.png) Unnecessary margin and occupying too much space in the screen. Also when previewed on a mobile phone the text are too small to be read & interact with. See the [reference](https://cncpaint.ph/) on the mobile view.

**Comment by kieruu** [comment]
Its fix i guess...
![galaxy-s5](https://user-images.githubusercontent.com/53436705/71326335-2ce5b480-2534-11ea-9ea1-0626216e4748.png)
![iphone-x](https://user-images.githubusercontent.com/53436705/71326336-2ce5b480-2534-11ea-822a-6a14e74597b7.png)
![pixel-2](https://user-images.githubusercontent.com/53436705/71326337-2d7e4b00-2534-11ea-8da1-eea7df5a32a9.png)

**Comment by noahjames404** [comment]
I already checked the code, it's working properly.
![thumbs up](https://cdn130.picsart.com/285667537030201.png?r1024x1024)
